plugins {
    id 'io.github.themrmilchmann.curseforge-publish'
}

def rootProps = new Properties()
def rootPropsFile = rootProject.file("gradle.properties")
if (rootPropsFile.exists()) {
    rootPropsFile.withReader { rootProps.load(it) }
}

def localProps = new Properties()
def localPropsFile = rootProject.file("local.properties")
if (localPropsFile.exists()) {
    localPropsFile.withReader { localProps.load(it) }
}

def token = localProps.getProperty('CURSEFORGE_TOKEN')
def project_id = localProps.getProperty('CURSEFORGE_ID')
def mod_version = rootProps.getProperty("version")
def mod_name = rootProps.getProperty("mod_name")
def release_mode = rootProps.getProperty("mod_release_type")

def changelogFile = rootProject.file("CHANGELOG.md")
def changelogContent = changelogFile.exists() ? changelogFile.text : "No changelog provided."

def uploadTask = tasks.named('jar') //tasks.findByName('remapJar')

curseforge {
    apiToken = "${token}"

    publications {
        register("curseForge") {
            projectId = "${project_id}"

            //gameVersions.add("${game_version}")

            artifacts.register("main") {
                from(uploadTask)

                displayName = "${mod_name} [${project.name.capitalize()}] - ${mod_version}"
                releaseType = "${release_mode}"

                //changelog = changelogContent
                //changelogType = 'markdown'

                changelog {
                    format = 'markdown'
                    content = changelogContent
                }

                relations {
                    embeddedLibrary("jilibs")
                    //incompatible("some-incompatible-mod-slug")
                    //optionalDependency("some-optional-dependency-slug")
                    //requiredDependency("some-required-dependency-slug")
                    //tool("some-tool-slug")
                }
            }
        }
    }
}

tasks.register('curseforge') {
    group = 'publishing'
    description = "Publishes ${project.name} artifacts to CurseForge."
    dependsOn(tasks.named('publishToCurseForge'))
}