# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

#======================================================= GRADLE
# Gradle     Latest : https://gradle.org/releases/
org.gradle.jvmargs=-Xmx2G -XX:+UseG1GC
org.gradle.daemon=false

#======================================================= GRADLE PLUGINS
# DON'T FORGET : Update the versions in gradle/wrapper/gradle-wrapper.properties for gradle version
# Spotless   Latest : https://plugins.gradle.org/plugin/com.diffplug.spotless
spotless_version=8.9.0

# Curseforge Latest : https://plugins.gradle.org/plugin/com.matthewprenger.cursegradle
cursegralde_version=0.11.0

# Modrinth   Latest : https://plugins.gradle.org/plugin/com.modrinth.minotaur
minotaur_version=2.9.0

# Fabric     Latest : https://mvnrepository.com/artifact/net.fabricmc/fabric-loom/versions
loom_version=1.18.2

# Neoforge   Latest : https://projects.neoforged.net/neoforged/moddevgradle
neoforge_plugin_version=2.0.148

#======================================================= MIXIN
# https://github.com/LlamaLad7/MixinExtras/tree/master/mixin-versions
spongepowered_version=0.8.7
# https://github.com/LlamaLad7/MixinExtras/releases
mixinextras_version=0.5.5

#======================================================= MINECRAFT
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
minecraft_version=26.3
java_version=25
# [26.3]
minecraft_version_range=[26.3, 26.4)

#======================================================= FABRIC
# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.162.0+26.3
fabric_loader_version=0.19.5

#======================================================= NEOFORGE
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.3-1
# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.3.0.57-beta
neoforge_loader_version_range=[4,)

#======================================================= MOD - Temp Mod
# https://modrinth.com/mod/materia
mod_id=materia
mod_name=Materia
group=com.dynamero.materia
version=26.3.1.1
mod_author=TheMentor
mod_license=LGPL-3.0

mod_credits=The Mentor
mod_description=The material and ingredient provider for Ars Mundi ecosystem.

# Release Type can be: 'release', 'beta', 'alpha'
mod_release_type=release

#======================================================= DEPENDENCIES
#=============================== JILIBS
jilibs_version=26.3.1.0

#=============================== ENERGY - FABRIC ONLY
# https://maven.fabricmc.net/teamreborn/energy/
energy_version=5.0.0

#=============================== PAL - FABRIC ONLY ?
# https://github.com/Ladysnake/PlayerAbilityLib/releases
pal_version=1.16.0

#=============================== MOD MENU - FABRIC ONLY
# https://modrinth.com/mod/modmenu
modmenu_version=21.0.0

#=============================== BADGES - FABRIC ONLY
# https://modrinth.com/mod/modmenu-badges-lib
badges_lib_version=2026.3.1

#=============================== KRYPTONAUGHT - FABRIC ONLY ?
# https://github.com/kyrptonaught/customportalapi
#kyrptonaught_version=0.0.1-beta68-1.21.8

#=============================== JADE
# https://www.curseforge.com/minecraft/mc-mods/jade/files/all?page=1&pageSize=20
jade_fabric_version=9042194
jade_neoforge_version=9042207
#=============================== JEI
# https://github.com/mezz/JustEnoughItems
jei_mc_version=26.3
jei_fabric_version=31.9.0.58
jei_neoforge_version=31.9.0.58

#=============================== EMI
# https://modrinth.com/mod/emi
#emi_fabric_version=1.1.22+1.21.1
#emi_neoforge_version=1.1.22+1.21.1

#=============================== REI
# https://maven.shedaniel.me/me/shedaniel/RoughlyEnoughItems-api-fabric/
# https://modrinth.com/mod/rei
rei_fabric_version=26.3.823
rei_neoforge_version=26.3.823

#=============================== CLOTH CONFIG
# https://maven.shedaniel.me/me/shedaniel/cloth/cloth-config-fabric/
# https://modrinth.com/mod/cloth-config
cloth_fabric_version=26.3.159
cloth_neoforge_version=26.3.159

#=============================== ARCHITECTURY
# https://modrinth.com/mod/architectury-api
architectury_fabric_version=22.0.4
architectury_neoforge_version=22.0.4

#=============================== TERRABLENDER
# https://modrinth.com/mod/terrablender
terrablender_fabric_version=26.3.0.0.9
terrablender_neoforge_version=26.3.0.0.9